# Generated by Django 2.0.1 on 2018-02-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180201_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=110, verbose_name='Titulo'),
        ),
    ]
