# Generated by Django 2.0.1 on 2018-02-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180207_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='tag',
            name='public',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Publicado'),
        ),
    ]
