# Generated by Django 2.0.1 on 2018-02-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180207_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Principiante'), (2, 'Intermedio'), (3, 'Avanzado')], null=True, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=110, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=210, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
