# Generated by Django 2.0.1 on 2018-02-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180214_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Principiante'), (2, 'Intermedio'), (3, 'Avanzado')], db_index=True, null=True, verbose_name='Nivel'),
        ),
    ]
