# Generated by Django 2.0.1 on 2018-03-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180226_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'solución', 'verbose_name_plural': 'soluciones'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dev-media', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Encabezado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=110, unique=True, verbose_name='Título'),
        ),
    ]
