# Generated by Django 2.0.1 on 2018-03-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180306_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/dev-media', verbose_name='Imagen'),
        ),
    ]
